# Generated by Django 5.2 on 2025-05-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_product_description_alter_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-time_create'], name='market_prod_time_cr_c7a8e5_idx'),
        ),
    ]
