# Generated by Django 5.2 on 2025-05-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
